springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/twitter
    password: cristian
  jpa:
    ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false